# Generated by Django 5.2.7 on 2025-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('carrera', models.CharField(blank=True, max_length=120)),
                ('semestre', models.PositiveIntegerField(default=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
