# Generated by Django 5.2.7 on 2025-10-06 00:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfilestudiante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))]),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))]),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))]),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='nota4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))]),
        ),
    ]
